# Generated by Django 4.0.4 on 2022-06-29 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=55)),
                ('phone', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=15)),
                ('time', models.CharField(max_length=12)),
                ('people', models.IntegerField()),
                ('message', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Qrcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=55)),
                ('phone', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=15)),
                ('time', models.CharField(max_length=12)),
                ('people', models.IntegerField()),
                ('message', models.TextField(max_length=255)),
            ],
        ),
    ]
